# Generated by Django 4.1.6 on 2023-02-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
    ]
